<?php

function ioch_languages() {
	
	$languages = array(
		"php" => "PHP",
		"markup" => "HTML",
		"css" => "CSS",
		"java" => "Java",
		"javascript" => "JavaScript",
		"apacheconf" => "Apache Config",
		"bash" => "Bash/Shell",
		"basic" => "BASIC",
		"c" => "C-like",
		"csharp" => "C#",
		"cpp" => "C++",
		"dart" => "Dart",
		"django" => "Django",
		"docker" => "Docker",
		"fsharp" => "F#",
		"graphql" => "GraphQL",
		"go" => "Go",
		"haskell" => "Haskell",
		"json" => "JSON",
		"kotlin" => "Kotlin",
		"lisp" => "Lisp",
		"markdown" => "Markdown",
		"matlab" => "MATLAB",
		"nginx" => "nginx",
		"objectivec" => "Objective-C",
		"powershell" => "PowerShell",
		"properties" => ".properties",
		"python" => "Python",
		"jsx" => "React JSX",
		"rest" => "reST (reStructuredText)",
		"ruby" => "Ruby",
		"sass" => "Sass",
		"sql" => "SQL",
		"svg" => "SVG",
		"swift" => "Swift",
		"toml" => "TOML",
		"typescript" => "TypeScript",
		"vim" => "vim",
		"visual-basic" => "Visual Basic",
		"wasm" => "WebAssembly",
		"wiki" => "Wiki markup",
		"xml" => "XML",
		"yaml" => "YAML",
	);
	return $languages;
}
